name: action-workflow
on:
  workflow_dispatch:
    
jobs:
    action-job:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository code
          uses: actions/checkout@v6.0.1
        
        - name: run a command in ubuntu vm
          run: echo "Hello from ubuntu vm!"

        - name: use a docker container
          uses: docker://alpine:3.17
          with:
            entrypoint: /bin/sh
            args: echo "Hello from alpine container!" 
    
    dockerized-action-job:
        runs-on: ubuntu-latest
        container: node:20
        steps:
        - name: node & npm version
          run: | 
            node --version
            npm --version 
        
        - name: use a custom dockerized action
          run: echo "Hello from custom dockerized action!"        

