name: sechdeld-workflow
on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
    scheduled-build-job:
        runs-on: ubuntu-latest
        steps:
        - name: Say Hello from scheduled job
          run: echo "Hello from scheduled job!"