name: sechdeld-workflow
on:
  schedule:
    - cron: '48 * * * *'  # Runs daily at every minute UTC

jobs:
    scheduled-build-job:
        runs-on: ubuntu-latest
        steps:

        - name: Say Hello from scheduled job
          run: echo "Hello from scheduled job!"