name: strategy-workflow

on:
  workflow_dispatch:

jobs:
    strategy-job:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        max-parallel: 3
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          node: [16.x, 18.x, 20.x]
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4  

        - name: Setup Node.js ${{ matrix.node }}
          uses: actions/setup-node@v3   
          with:
            node-version: ${{ matrix.node }}

        - name: Display OS and Node.js version
          run: |
            echo "Running on ${{ matrix.os }} with Node.js version:"
            node --version  